version: '3'
services:
  web: # web server 80
    image: leon1234858/ourchain-web-cli
    ports:
      - "8000:80"
    networks:
      my_network:
        ipv4_address: 172.16.238.9
  webapi: # web api 8080
    image: leon1234858/ourchain-agent
    ports:
      - "8080:8080"
    networks:
      my_network:
        ipv4_address: 172.16.238.10
    environment:
      APP_HOST: 172.16.238.11
  chain: # chain server connected by web api
    image: leon1234858/our-chain
    ports:
      - "8332:8332"
    networks:
      my_network:
        ipv4_address: 172.16.238.11
    volumes:
      - node_data:/root/.bitcoin
  miner_service:
    image: node:lts-alpine3.19  # 使用官方 Node.js 镜像
    volumes:
      - ./script/miner.mjs:/root/script.mjs
    command: [ "node", "/root/script.mjs" ]
    networks:
      my_network:
        ipv4_address: 172.16.238.12

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
volumes:
  node_data:
    external: true
